server:
  port: 8082

spring:
  application:
    name: video-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: secret
    url: jdbc:postgresql://localhost:5432/video-service
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
